/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contactManager2Sol from "./ContactManager2.sol";
export type { contactManager2Sol };
import type * as contractManagerSol from "./ContractManager.sol";
export type { contractManagerSol };
export type { ContractManagerAccess } from "./ContractManagerAccess";
export type { NFTToolbox } from "./NFTToolbox";
