/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contactManagerSol from "./ContactManager.sol";
export type { contactManagerSol };
export type { NFTToolbox } from "./NFTToolbox";
