/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contractManagerSol from "./ContractManager.sol";
export type { contractManagerSol };
export type { NFTToolbox } from "./NFTToolbox";
