/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  MIERC721,
  MIERC721Interface,
} from "../../../contracts/ContractManager.sol/MIERC721";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_newItemId",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class MIERC721__factory {
  static readonly abi = _abi;
  static createInterface(): MIERC721Interface {
    return new utils.Interface(_abi) as MIERC721Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MIERC721 {
    return new Contract(address, _abi, signerOrProvider) as MIERC721;
  }
}
